const arr=[1,3,4,5,8,9];

const newArr= arr.map(function(item,index){
    return item + index;
});

console.log(newArr);
//Total é o currenc

const sum = arr.reduce(function(total,next){
    return total + next;
});

console.log(sum);
//Retornando so os pares
const filter = arr.filter(function(item){
    return item % 2 === 0;
});
console.log(filter);

const find = arr.find(function(item){
    return item === 2;
});

console.log(find);